# Generated by Django 4.1.7 on 2023-03-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=50)),
                ('anioLanzamiento', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Director.director')),
            ],
        ),
    ]
