# Generated by Django 4.1.7 on 2023-03-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pelicula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='rentable',
            field=models.BooleanField(default=False),
        ),
    ]
